# Generated by Django 4.0.6 on 2022-07-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='paymethod',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
