# Generated by Django 4.0.5 on 2022-08-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0003_rename_trans_type_transactions_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='ref',
            field=models.CharField(blank=True, default='EN-8F5EF839-D', max_length=50, null=True),
        ),
    ]
