# Generated by Django 4.0.5 on 2022-08-06 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0004_transactions_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_name', models.CharField(blank=True, max_length=50, null=True)),
                ('acc_num', models.CharField(blank=True, max_length=50, null=True)),
                ('ty_pe', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='transactions',
            name='ref',
            field=models.CharField(blank=True, default='EN-4D0D6CA9-8', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='bank_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans_bank', to='userdashboard.bank'),
        ),
    ]
